// ─────────────────────────────────────────────────────────────────────────────
// MAP PINS — each photo anchors one full resume section to its real location.
// ─────────────────────────────────────────────────────────────────────────────
const PINS = [
  {
    id: "tel-aviv",
    lat: 32.0853,
    lng: 34.7818,
    location: "Tel Aviv, Israel",
    thumb: "images/pins/tel-aviv.jpg",
    photo: "images/gallery/tel-aviv.jpg",
    year: "2023 – Present",
    role: "Volunteering",
    org: "Maguen David Adom · Yad Rajamim · ITAM Teaching Assistant",
    category: "volunteer",
    color: "#bc8cff",
    description: "From emergency ambulances in Israel to teaching English to vulnerable children in Mexico City — volunteering has been a constant thread throughout my journey.",
    details: [
      { label: "Maguen David Adom — Israel", text: "Served on emergency ambulances, prepared equipment, and administered first aid in high-pressure environments. Earned First Responder certification." },
      { label: "Yad Rajamim — Mexico City", text: "Teaching English to vulnerable children, equipping them with tools for future academic success. Jan 2024 – Present." },
      { label: "Teaching Assistant — ITAM", text: "Providing support to students in the fundamentals of finance course. Jan 2025 – Present." },
    ],
    skills: ["Emergency Response", "First Aid", "Teaching", "Community Impact", "Trauma Care"],
  },
  {
    id: "guatemala",
    lat: 14.6349,
    lng: -90.5069,
    location: "Guatemala City, Guatemala",
    thumb: "images/pins/guatemala.jpg",
    photo: "images/gallery/guatemala.jpg",
    year: "2023 – Present",
    role: "Education",
    org: "ITAM · Colegio Hebreo Tarbut",
    category: "education",
    color: "#f78166",
    description: "My academic path has been defined by curiosity across disciplines — combining the rigour of finance with the power of data science, while grounding everything in strong foundational values.",
    details: [
      { label: "ITAM — Mexico City", text: "Dual Bachelor's Degree in Finance and Data Science. Expected completion January 2028. Bloomberg Market Concepts certified (2024)." },
      { label: "Colegio Hebreo Tarbut — Mexico City", text: "High School Diploma, graduated with honours, June 2023." },
    ],
    skills: ["Financial Analysis", "Data Science", "Python", "Java", "SQL", "SAP"],
  },
  {
    id: "seattle",
    lat: 47.6062,
    lng: -122.3321,
    location: "Seattle, USA",
    thumb: "images/pins/seattle.jpg",
    photo: "images/gallery/seattle.jpg",
    year: "2020 – Present",
    role: "Work Experience",
    org: "J.P. Morgan · Daclaf · Grupo Kessel",
    category: "work",
    color: "#58a6ff",
    description: "Four years of hands-on professional experience — from executive strategy to financial operations to equity research — each role building on the last.",
    details: [
      { label: "J.P. Morgan — Equity Research Intern", text: "Supporting financial analyses and company valuations across key sectors. Preparing research reports and monitoring quarterly earnings and macroeconomic trends. Mar 2026 – Present." },
      { label: "Daclaf — Finance Intern", text: "Supporting financial operations and internal reporting. Contributing to budget tracking, cost-control initiatives, and operational performance analysis. Aug 2025 – Feb 2026." },
      { label: "Grupo Kessel — Assistant to the CEO", text: "Preparing monthly progress reports, identifying investment opportunities, and assisting in research and planning of new business strategies. Jan 2021 – Aug 2025." },
    ],
    skills: ["Financial Modeling", "Equity Analysis", "Investment Research", "Budget Management", "Strategic Planning"],
  },
  {
    id: "acapulco",
    lat: 16.8531,
    lng: -99.8238,
    location: "Acapulco, Mexico",
    thumb: "images/pins/acapulco.jpg",
    photo: "images/gallery/acapulco.jpg",
    year: "2020 – Present",
    role: "Drone Photography",
    org: "Drone Photography MX · Founder",
    category: "project",
    color: "#39d353",
    description: "Aerial photography is not just a hobby — it's how I see the world differently. I launched a commercial drone photography business and have been capturing perspectives that can't be seen from the ground ever since.",
    details: [
      { label: "Drone Photography MX — Founder", text: "Launched and operated a commercial drone photography business for professional aerial projects. Managed client relations and post-production workflows. Feb 2020 – Dec 2021." },
      { label: "The Passion Continues", text: "Every photo on this map was taken with a drone. Each location tells a story — not just of a place, but of a moment in my life." },
    ],
    skills: ["Drone Piloting", "Aerial Photography", "Entrepreneurship", "Client Relations", "Photo Editing"],
  },
  {
    id: "malinche-puebla",
    lat: 19.2333,
    lng: -98.0167,
    location: "La Malinche, Puebla, Mexico",
    thumb: "images/pins/malinche-puebla.jpg",
    photo: "images/gallery/malinche-puebla.jpg",
    year: "2022 – 2024",
    role: "Leadership & Projects",
    org: "Model United Nations · Synagogue Renovation Project",
    category: "project",
    color: "#d29922",
    description: "Leadership is about bringing people together toward a shared goal. Whether directing 300 delegates or modernising a community space, these experiences shaped how I think about ownership and impact.",
    details: [
      { label: "Model United Nations — Under Secretary General", text: "Directed a Model United Nations conference involving 300 delegates from 5 schools. Oversaw all committee activities and ensured diplomatic protocol compliance. Aug 2023 – Jun 2024." },
      { label: "Synagogue Renovation — Project Lead", text: "Led a fundraising campaign and supervised architectural updates to modernise the synagogue space, resulting in greater student engagement. Aug 2022 – Mar 2023." },
    ],
    skills: ["Leadership", "Event Management", "Public Speaking", "Fundraising", "Project Coordination"],
  },
  {
    id: "la-paz",
    lat: 24.1426,
    lng: -110.3128,
    location: "La Paz, Baja California Sur, Mexico",
    thumb: "images/pins/la-paz.jpg",
    photo: "images/gallery/la-paz.jpg",
    year: "Skills",
    role: "Skills & Languages",
    org: "Technical · Languages · Certifications",
    category: "project",
    color: "#39d353",
    description: "A toolkit built across finance, technology, and cross-cultural communication — developed through real-world experience and continuous learning.",
    details: [
      { label: "Technical Skills", text: "Python · Java · SQL · SAP · Financial Modeling · Equity Research" },
      { label: "Languages", text: "Spanish — Native · English — Fluent · Hebrew — Intermediate" },
      { label: "Certifications", text: "Bloomberg Market Concepts (2024) · First Responder — Israel (2023)" },
    ],
    skills: ["Python", "Java", "SQL", "SAP", "Spanish", "English", "Hebrew"],
  },
  {
    id: "cdmx",
    lat: 19.4326,
    lng: -99.1332,
    location: "Mexico City, Mexico",
    thumb: "images/pins/cdmx.jpg",
    photo: "images/gallery/cdmx.jpg",
    year: "2023 – 2024",
    role: "Certifications",
    org: "Bloomberg · First Responder Israel",
    category: "education",
    color: "#f78166",
    description: "Two certifications that reflect two very different dimensions of who I am — one in global financial markets, one in life-saving emergency care.",
    details: [
      { label: "Bloomberg Market Concepts (2024)", text: "Comprehensive certification covering economics, currencies, fixed income, and equity markets through the Bloomberg terminal." },
      { label: "First Responder — Israel (2023)", text: "Certified in emergency care and trauma response during my volunteer service with Maguen David Adom in Israel." },
    ],
    skills: ["Bloomberg Terminal", "Financial Markets", "Emergency Care", "Trauma Response"],
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// GALLERY — all drone photos for the photography showcase.
// ─────────────────────────────────────────────────────────────────────────────
const GALLERY = [
  { id: "g1", src: "images/gallery/tel-aviv.jpg",       thumb: "images/pins/tel-aviv.jpg",        location: "Tel Aviv, Israel",              date: "2023", caption: "The coastline of Tel Aviv — a city that never stops moving, seen from above." },
  { id: "g2", src: "images/gallery/guatemala.jpg",      thumb: "images/pins/guatemala.jpg",       location: "Guatemala City, Guatemala",     date: "2023", caption: "Ancient meets modern over the Guatemalan skyline." },
  { id: "g3", src: "images/gallery/seattle.jpg",        thumb: "images/pins/seattle.jpg",         location: "Seattle, USA",                  date: "2023", caption: "The Pacific Northwest from altitude — mountains, water, and city all at once." },
  { id: "g4", src: "images/gallery/acapulco.jpg",       thumb: "images/pins/acapulco.jpg",        location: "Acapulco, Mexico",              date: "2021", caption: "Where the Pacific meets the cliffs — Acapulco from a drone's eye view." },
  { id: "g5", src: "images/gallery/malinche-puebla.jpg",thumb: "images/pins/malinche-puebla.jpg", location: "La Malinche, Puebla, Mexico",   date: "2022", caption: "The ancient volcano La Malinche rising through the clouds over Puebla." },
  { id: "g6", src: "images/gallery/la-paz.jpg",         thumb: "images/pins/la-paz.jpg",          location: "La Paz, Baja California Sur",   date: "2021", caption: "Crystal waters and desert shores — La Paz from above." },
  { id: "g7", src: "images/gallery/cdmx.jpg",           thumb: "images/pins/cdmx.jpg",            location: "Mexico City, Mexico",           date: "2020", caption: "The megalopolis — 21 million lives unfolding beneath the drone." },
];
